github:
    user: willsalmanj
    repo: zutilo
    token: deploy/github.token
    assets:
    - path: build/zutilo.xpi
      type: application/x-xpinstall

git_release:
    remote: origin
    branch: release

version_strings:
- path: addon/install.rdf
  pattern: (<em:version>)(?P<release>.*)(</em:version>)
- path: deploy/update.rdf
  pattern: (<em:version>)(?P<release>.*)(</em:version>)
- path: deploy/update.rdf
  pattern: (<em:updateLink>https://github.com/willsALMANJ/Zutilo/releases/download/v)(?P<release>.*)(/zutilo.xpi</em:updateLink>)
- path: package.json
  pattern: '^(  "version": ")(?P<release>.*)(",)$'
- path: package-lock.json
  pattern: '^(  "version": ")(?P<release>.*)(",)$'
